### ISSUE TITLE
GIT上启动起来的界面和DEMO界面不一致，是还没提交完全吗？

### ISSUE THREAD

**Issue by Daniells8910** [synyi/poplar#10]
![image](https://user-images.githubusercontent.com/26462154/44296968-5d439000-a2fb-11e8-98ad-4536e21e33b8.png)

**Comment by longfangsong** [comment]
@Daniells8910 Github仓库中的源码并非Demo源码，而是npm包源码，启动后只能看到开发过程中的测试页面。
[在这里查看npm包](https://www.npmjs.com/package/poplar-annotation)
Demo就是使用了这个npm包制作的。
这一版本为beta版，等v1版本完成后，将在新的分支中上传demo源码。
