### ISSUE TITLE
同一个词重复标记问题

### ISSUE THREAD

**Issue by felixhpp** [synyi/poplar#11]
您好，首先非常感谢您的开源项目，在您的demo中同一个词可以重复标记，请问是有这样的业务需求吗？

![image](https://user-images.githubusercontent.com/10015885/44824188-dd8cbe00-ac36-11e8-8018-5323180afd6b.png)

**Comment by longfangsong** [comment]
@felixhpp 因为同一个词可以有多个正交的`Category`，所以我们允许重复标记同一个词
如果要禁止这么做，可以在客户代码中进行，方法是在添加过程中检测`Store`中是否有这个`Label`
如果发现大部分用户都希望不允许重复标记同一个词，我们会考虑加入这个功能（或者让它`configable`）

**Comment by grzhan** [comment]
@felixhpp 公司在业务上会有这个需求，标注时可能会有不同语义层级的 `Category`

**Comment by felixhpp** [comment]
@longfangsong 嗯，非常感谢。期待以后可以加一个通过配置控制

**Comment by longfangsong** [comment]
从npm版本v1.3.0之后，在`config`中设置`allowMultipleLabel`为`false`可以不允许重复标记同一个词。
@felixhpp

**Comment by Wuou** [comment]
nice 重复标注可以配置了
