### ISSUE TITLE
字符长度过长导致标注无法渲染出来

### ISSUE THREAD

**Issue by HazyGuo** [synyi/poplar#12]
作者您好，我运行您的demo分支代码发现一个问题，我输入一个新的文本（非样本文件）之后，进行标注，label能被添加到json文件中，但是左侧页面上确没有高亮出来，请问这个问题您能帮忙解决一下吗？看您源代码上好像加了TODO

**Comment by grzhan** [comment]
方便的话可以提供下文本文件（或去敏的同样长度格式的文件）么

**Comment by HazyGuo** [comment]
[FeHelper-20180910194354.txt](https://github.com/synyi/poplar/files/2378129/FeHelper-20180910194354.txt)
将txt重命名为json文件

**Comment by longfangsong** [comment]
问题的原因在于多个连续空白字符和全角空白字符，它会使getExtentOfChar工作不正常

新版本（npm v1.2.2）应该已经修复了这一问题。

commit 1dcd369 should fixed this.

**Comment by HazyGuo** [comment]
非常感谢~
