### ISSUE TITLE
相邻标注时，会出现后面标注的高度会比前面的高，这就导致最下面的一行会被挤的显示不全的问题

### ISSUE THREAD

**Issue by idliuyang** [synyi/poplar#13]
![image](https://user-images.githubusercontent.com/20554550/46000389-fc1d9200-c0da-11e8-8d65-8273a7774ce1.png)
![image](https://user-images.githubusercontent.com/20554550/46000402-08a1ea80-c0db-11e8-91a0-0a6487f9d3ee.png)

首先很感谢您开源此项目，我在开发中发现，当前面标注的过程中，出现图类似的情况的时候，最下面的一行或者几行会被挤出去，在您的demo中也会出现类似的情况，请问这种问题怎么解决，谢谢！

**Comment by longfangsong** [comment]
为svg元素添加overflow: scroll;即可
我们将在下一版本中这么做

**Comment by longfangsong** [comment]
Fixed in v1.2.5
在npm版本1.2.5中修复了这个问题
@idliuyang

**Comment by longfangsong** [comment]
在线Demo已一并更新
