### ISSUE TITLE
中文中出现小数点的情况

### ISSUE THREAD

**Issue by idliuyang** [synyi/poplar#16]
在标注的过程中，中文中出现了小数点的情况，会导致直接换行的情况，这个能够做出合理的判断吗？
另外，现在的版本中，在chrome浏览器上，划词功能选中的高亮样式好像没有了，只能看到划词开始的位置，而并看不到划词结束的位置，这个需要怎么解决呢？

**Comment by wangjunji** [comment]
我也碰到了，Safari中可以看得到选词的高亮，Chrome里选词拖拽只能看到第一个字符被高亮

**Comment by idliuyang** [comment]
> 我也碰到了，Safari浏览器中可以看得到选词的高亮，Chrome浏览器里选词拖拽只能看到第一个字符被高亮
我在火狐上也测试了，划词本身没有问题，但是label会变小，不能容纳所有显示在label里面的内容，另外，你有办法禁止掉两个label相互连接的那个箭头的功能么？我看api里面没有做这个功能相关禁止的介绍。

**Comment by idliuyang** [comment]
标注后的label可以被左键点击后出现一个箭头连接另外一个label，我并不想要这个功能，你那边知道怎么禁止吗？我在api里面好像没有找到禁止的方法。
----- 原始邮件 -----
发件人：Ken <notifications@github.com>
收件人：synyi/poplar <poplar@noreply.github.com>
抄送人：devin <hkccly2@sina.com>,  Author <author@noreply.github.com>
主题：Re:_[synyi/poplar]_中文中出现小数点的情况_(#16)
日期：2018年12月18日 22点55分

我也碰到了，Safari中可以看得到选词的高亮，Chrome里选词拖拽只能看到第一个字符被高亮



&mdash;

**Comment by Gongkaikai** [comment]
> 在标注的过程中，中文中出现了小数点的情况，会导致直接换行的情况，这个能够做出合理的判断吗？
> 另外，现在的版本中，在chrome浏览器上，划词功能选中的高亮样式好像没有了，只能看到划词开始的位置，而并看不到划词结束的位置，这个需要怎么解决呢？

谷歌浏览器划词功能的bug突然正常了，不知道哪里做了改动

**Comment by 2638720389** [comment]
请问一下，这个项目怎么让它运行起来呢

**Comment by dllmm** [comment]
大佬们 请问小数点换行的问题解决了伐

**Comment by dllmm** [comment]
今天看了下源码 poplar\src\Annotator\Store\Entities路径下的Line.ts中的第65行！!。.？?"\n这里把.去掉还有第70行！!。.？?”"a-zA-Z这里也把.去掉 小数点就不会换行了 demo中找到vendor.6884fc746c954a8feea5.js这个文件和源码Line.ts第65、70行相对应的地方改掉就可以了

**Comment by lvjunxiang** [comment]
可以教我一下怎么用这个工具吗？我按照开发文档，在js中导入，然后就报错了(qq:1216498454)

**Comment by longfangsong** [comment]
fixed in v2
