### ISSUE TITLE
v2意见征集

### ISSUE THREAD

**Issue by longfangsong** [synyi/poplar#31]
本人目前正在开发v2版本

希望能新增的内容是：

- 更小的包大小（通过移除svg.js和rxjs的依赖）
- 更好的换行策略 (#26, #32)
- 自适应行距 (#29)
- 更多的可配置项，包括
  - 行距 (#29)
  - 所有的字体（内容、Label、Connection）(#15)
  - 给内容、Label和Connection添加自定义class
  - Label的padding
  - 是否允许同两个Label间的重复Connection(#21)
  - 各种功能是否启用(#19)
- 允许自定义Action
- 更多事件
- 内容编辑功能(#33)
- 更详尽的文档(#23,#24,#25,#28)

如果有相关建议或意见，欢迎在本issue或其他issue中提出。

（目前已经有了不使用svg.js和rxjs，支持自适应行距、配置所有字体的demo版，代码已经上传至v2分支）

**Comment by smartcatdog** [comment]
想问下这个项目标注是人工标注嘛还是说有什么算法呢，因为没看到算法在

**Comment by longfangsong** [comment]
@smartcatdog
这是一个用于手动标注的工具，可以用来人工标注或 展示/修改 自动/手动 标注的结果

**Comment by wayw** [comment]
label添加删除按钮，右键事件删除不友好。
label显示位置也可以直接加到选择文本的后面。类似Prodigy

**Comment by longfangsong** [comment]
@wayw
在v2中，右键label（和connection）将会作为一个事件被emit出来，让用户发送action进行删除
可以拦截这个事件然后弹出菜单等
label显示位置在选择文本的后面的问题，在允许加互相重叠的label的情况下，这种显示方式可能会有一点混乱，且在目前架构下实现存在一定困难，v2中不会实现这一功能，将在未来版本中考虑

**Comment by MrRace** [comment]
希望增加一个功能：支持阅读理解任务中答案span的标注。

**Comment by ljtlrh** [comment]
运行不起

**Comment by snakesgun** [comment]
是否有考虑增加跨词标注的功能，类似brat中的add fragement

**Comment by quietmango** [comment]
想请问下，这个组件在angular中可以用么？有没有特别的配置要求？将组件引入angular工程，在调用this.annotator.applyAction(Action.Label.Create(this.selectedLabelCategory, this.startIndex, this.endIndex));时，会报奇怪的错误，像这样子：
![image](https://user-images.githubusercontent.com/30401216/75510310-803d1d00-5a25-11ea-9ff1-979e4a474233.png)

**Comment by chendong0** [comment]
1.在ubuntu系统张已按步骤安装node
2.V2版本中按[readme.md](https://github.com/synyi/poplar/tree/v2.0.3#readme)操作了，运行不了。
3.这个项目只能使用demo来使用吗？https://synyi.github.io/poplar/
