### ISSUE TITLE
換行問題

### ISSUE THREAD

**Issue by nissenyeh** [synyi/poplar#34]
你好，在maxLineWidth正確設定的狀況下，偶爾會有無法換行的情況，推測可能是因為文字有label，所以無法換行。請問這是Bug嗎？

![image](https://user-images.githubusercontent.com/34571901/62911094-9949ed80-bdb5-11e9-9677-f7dea0dce5f9.png)

**Comment by longfangsong** [comment]
设计上我们不希望把一个Label从中间断开分到两行上（这样看起来不太好看，代码里也比较难处理）。
在加上某个Label后，若行宽超过`maxLineWidth`，会把这个Label放到下一行。
当然如果单个或一组互相交叠的Label长度已经超过了`maxLineWidth`，则无法正常分行（此时v1的行为我已经记不清了，v2的行为是仍然渲染出这个超长的行）。

**Comment by playma** [comment]
v2 已解決換行問題，但換行後最左邊的 label 有可能會被切掉

**Comment by longfangsong** [comment]
@playma 
07f079e 添加了padding的自适应，根据最长的label计算padding，保证label不会被切掉。
<img width="551" alt="屏幕快照 2020-02-14 下午9 32 31" src="https://user-images.githubusercontent.com/13777628/74536022-2b53ce00-4f72-11ea-9a43-f6f4bba20316.png">
