### ISSUE TITLE
是否支持disable实体关系

### ISSUE THREAD

**Issue by xingbofeng** [synyi/poplar#37]
两个实体关系不允许进行连接的配置，比如A不允许和B连接，也不允许和相同类型进行连接

**Comment by xingbofeng** [comment]
或者说可以连接的实体配置

**Comment by longfangsong** [comment]
@xingbofeng 可以在`twoLabelsClicked`事件中进行处理来达到这种效果
比如从`labelRepo`中获取这两个`label`，再根据其`categoryId`来判断是否允许添加连接
关于是否将这一功能内置，我需要考虑一下
