### ISSUE TITLE
内容部分的padding可以设置吗？

### ISSUE THREAD

**Issue by exdestroyer** [synyi/poplar#47]
目前内容部分好像自带一定的padding，能否根据业务需求自行调节？

**Comment by longfangsong** [comment]
@exdestroyer 目前padding大小不能调节，将在未来版本中添加

**Comment by longfangsong** [comment]
@exdestroyer 
07f079e 添加了padding的自适应，根据最长的label计算padding，保证label不会被切掉。
<img width="551" alt="屏幕快照 2020-02-14 下午9 32 31" src="https://user-images.githubusercontent.com/13777628/74536022-2b53ce00-4f72-11ea-9a43-f6f4bba20316.png">
