### ISSUE TITLE
连线和选中的文字的颜色怎么修改, 文档里没有找到相关的配置项？

### ISSUE THREAD

**Issue by exdestroyer** [synyi/poplar#48]
连线的颜色怎么修改, 文档里没有找到相关的配置项？

**Comment by longfangsong** [comment]
@exdestroyer 目前连线颜色不能修改，将在未来版本中添加

**Comment by longfangsong** [comment]
@exdestroyer 
fixed in 8089775
见 [文档的CSS部分](https://github.com/synyi/poplar/blob/master/doc/zh.md#css)。
npm包将在下次发布（本月底）时更新。
