### ISSUE TITLE
DOMException: "Index or size is negative or greater than the allowed amount"

### ISSUE THREAD

**Issue by kinginsun** [synyi/poplar#56]
{"content": "The aim of the presented study was to characterize the anticonvulsant effects of levetiracetam in combination with various antiepileptic drugs (carbamazepine, phenytoin, topiramate and vigabatrin) in the mouse 6Hz psychomotor seizure model. Limbic (psychomotor) seizure activity was evoked in albino Swiss mice by a current (32mA, 6Hz, 3s stimulus duration) delivered via ocular electrodes; type II isobolographic analysis was used to characterize the consequent anticonvulsant interactions between the various drug combinations for fixed-ratios of 1:1, 1:2, 1:5 and 1:10. With type II isobolographic analysis, the combinations of levetiracetam with carbamazepine and phenytoin for the fixed-ratios of 1:5 and 1:10 were supra-additive (synergistic; P<0.01) in terms of seizure suppression, while the combinations for the fixed-ratios of 1:1 and 1:2 were additive. Levetiracetam combined with topiramate and vigabatrin for the fixed-ratio of 1:10 exerted supra-additive interaction (P<0.05), and simultaneously, the two-drug combinations for the fixed-ratios of 1:1, 1:2 and 1:5 produced additive interaction in the mouse 6Hz psychomotor seizure model. The combinations of levetiracetam with carbamazepine and phenytoin for the fixed-ratios of 1:5 and 1:10, as well as the combinations of levetiracetam with topiramate and vigabatrin for the fixed-ratio of 1:10 appear to be particularly favorable combinations exerting supra-additive interaction in the mouse 6Hz psychomotor seizure model. Finally, it may be concluded that because of the synergistic interactions between levetiracetam and carbamazepine, phenytoin, topiramate and vigabatrin, the combinations might be useful in clinical practice."}

上面为出问题的文本，上面只是出问题的一个例子。我用其中的多个部分进行测试可以正常标记，但是整体就会出错，文本区域只显示小量黑点，其他什么也没有。如下图所示：
<img width="1295" alt="WX20200227-114952@2x" src="https://user-images.githubusercontent.com/3724110/75410611-6f25da80-5957-11ea-991e-225c00799c90.png">

Firefox中console的错误为：
DOMException: "Index or size is negative or greater than the allowed amount"

Chrome中的错误为：
vue.runtime.esm.js:1888 DOMException: Failed to execute 'getExtentOfChar' on 'SVGTextContentElement': The charnum provided (47) is greater than or equal to the maximum bound (47).

**Comment by longfangsong** [comment]
> {"content": "The aim of the presented study was to characterize the anticonvulsant effects of levetiracetam in combination with various antiepileptic drugs (carbamazepine, phenytoin, topiramate and vigabatrin) in the mouse 6Hz psychomotor seizure model. Limbic (psychomotor) seizure activity was evoked in albino Swiss mice by a current (32mA, 6Hz, 3s stimulus duration) delivered via ocular electrodes; type II isobolographic analysis was used to characterize the consequent anticonvulsant interactions between the various drug combinations for fixed-ratios of 1:1, 1:2, 1:5 and 1:10. With type II isobolographic analysis, the combinations of levetiracetam with carbamazepine and phenytoin for the fixed-ratios of 1:5 and 1:10 were supra-additive (synergistic; P<0.01) in terms of seizure suppression, while the combinations for the fixed-ratios of 1:1 and 1:2 were additive. Levetiracetam combined with topiramate and vigabatrin for the fixed-ratio of 1:10 exerted supra-additive interaction (P<0.05), and simultaneously, the two-drug combinations for the fixed-ratios of 1:1, 1:2 and 1:5 produced additive interaction in the mouse 6Hz psychomotor seizure model. The combinations of levetiracetam with carbamazepine and phenytoin for the fixed-ratios of 1:5 and 1:10, as well as the combinations of levetiracetam with topiramate and vigabatrin for the fixed-ratio of 1:10 appear to be particularly favorable combinations exerting supra-additive interaction in the mouse 6Hz psychomotor seizure model. Finally, it may be concluded that because of the synergistic interactions between levetiracetam and carbamazepine, phenytoin, topiramate and vigabatrin, the combinations might be useful in clinical practice."}
> 
> 上面为出问题的文本，上面只是出问题的一个例子。我用其中的多个部分进行测试可以正常标记，但是整体就会出错，文本区域只显示小量黑点，其他什么也没有。如下图所示：
> <img alt="WX20200227-114952@2x" width="1295" src="https://user-images.githubusercontent.com/3724110/75410611-6f25da80-5957-11ea-991e-225c00799c90.png">
> 
> Firefox中console的错误为：
> DOMException: "Index or size is negative or greater than the allowed amount"
> 
> Chrome中的错误为：
> vue.runtime.esm.js:1888 DOMException: Failed to execute 'getExtentOfChar' on 'SVGTextContentElement': The charnum provided (47) is greater than or equal to the maximum bound (47).

这一问题发生的原因是`<` 被转义了。

立即修复。

**Comment by longfangsong** [comment]
已经可用。
![屏幕快照 2020-02-27 下午4 39 39](https://user-images.githubusercontent.com/13777628/75426540-d6578500-597f-11ea-8d25-a2cf5f6a3ef4.png)

**Comment by kinginsun** [comment]
这么快，牛
