### ISSUE TITLE
Failed to execute 'getExtentOfChar' on 'SVGTextContentElement'

### ISSUE THREAD

**Issue by jack0526** [synyi/poplar#58]
如题，测试文本如下，报如上的错误，直接渲染不出来：
双眼lpi孔通
tyn(+)
颜色可
右眼下方盘沿稍窄
右眼1级 上/下方盘沿稍窄
双眼注视眼位可
后巩膜葡萄肿
双眼外眼前节未见明显异常
相应处rnfld 左眼3级 上下方盘沿均变窄
瞳孔膜闭
双眼球突出
视盘斜入
瞳孔正常
双眼：滤过泡弥散
眼底视盘色淡
左眼盘沿形态未见明显异常
双眼高度近视眼底
左眼视盘水肿
右眼翼状胬肉
乳头+
左眼前节未见明显异常
直径6mm
眼底c/d=0.4
直径5mm
左眼1级 上/下方盘沿稍窄
色尚可
对光反射存
抵抗感（-）
右眼-
斜入
眼底窥视不清
晶体后囊轻混
眼球轻突出
瞳圆
双but< 5s
右眼晶体皮质楔形混浊
右眼rapd(+)
左眼注视
无充血
虹膜纹理清晰
左眼结膜下出血
右j4
视网膜血管细
微血管瘤
双眼黄斑区未见明显异常
瞳孔对光反射存在
双外眼未见明显异常
晶体表面色素沉着
前房深 双眼c/d＝05
眼底：双眼盘沿形态未见异常
右眼上/下方盘沿稍窄
余视不清
右眼滤过弥散
左眼角膜弥漫水肿
前房轴深中深
角膜明
根切孔可见
各方向可见大量激光斑
直径2mm
右眼色淡

![image](https://user-images.githubusercontent.com/28337513/75455522-77603300-59b4-11ea-9b9c-c93a975351e2.png)

**Comment by longfangsong** [comment]
可能是和 #56 一样的问题。
在修复#56后，demo页面中已经可以渲染。
对应 npm 版本号为v2.0.3。

**Comment by longfangsong** [comment]
@jack0526
可能是和 #56 一样的问题。
在修复 #56 后，demo页面中已经可以渲染。
对应 npm 版本号为v2.0.3。

<img width="1132" alt="屏幕快照 2020-02-27 下午11 22 24" src="https://user-images.githubusercontent.com/13777628/75458359-a1b3ef80-59b8-11ea-83ea-ff4455340e7f.png">

**Comment by jack0526** [comment]
更新版本后已解决，非常感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"龙方淞"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月27日(星期四) 晚上11:28
收件人:&nbsp;"synyi/poplar"<poplar@noreply.github.com&gt;;
抄送:&nbsp;"君子悠柠"<1263944153@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [synyi/poplar] Failed to execute 'getExtentOfChar' on 'SVGTextContentElement' (#58)




可能是和 #56 一样的问题。
 在修复 #56 后，demo页面中已经可以渲染。
 对应 npm 版本号为v2.0.3。
