### ISSUE TITLE
开源询问

### ISSUE THREAD

**Issue by cloudXia777** [synyi/poplar#8]
您好，现在贵公司poplar是没打算开源吗？那synyi版本是已经开源使用了吗？感谢

**Comment by grzhan** [comment]
您好，

Poplar 代码目前已经开源了，作为标注工具基本功能已经开发完毕，我们现在正在开发针对 Poplar 可用的界面版本，应该在这两天就可以发布。
届时请提出您的宝贵意见。

**Comment by cloudXia777** [comment]
非常感谢您的回信！感谢贵公司的开源思想！你们这边关于synyi的使用说明有更详细一些的吗？因为看到README写的有些简短。非常期待您们的标注工具的发布！

**Comment by grzhan** [comment]
@cloudXia777 不日会提供 demo 及具体的使用文档

**Comment by grzhan** [comment]
初步的 demo 请访问 https://synyi.github.io/poplar/ 使用
